project:
  type: book
  output-dir: docs

book:
  title: "Corso apprendimento automatico"
  author: "Antonio Montano"
  date: "3/30/2024"
  chapters:
    - index.qmd
    - part: 1.qmd
      chapters: 
        - 1.1.qmd
    - part: 2.qmd
      chapters:
        - 2.1.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: lux
  pdf:
    documentclass: scrreprt



